# Generated by Django 6.0.6 on 2026-07-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('total_courts', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_count', models.IntegerField(default=0)),
                ('disposed_count', models.IntegerField(default=0)),
                ('disposal_rate', models.FloatField(default=0.0)),
                ('avg_case_age_days', models.FloatField(default=0.0)),
                ('severity_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
            ],
        ),
    ]
